# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ec47524078cdd0debecc5e61a74add532c317540b80d99a56900c09626ab2fb6836a5bc0702eea8aa05f993fa14023acd22f4f8d467dc089c260fe6996ba13f

test:
  secret_key_base: 7d2904ac87c7d00aa104847b6839a450b1633f0488e3547a373a569af7a6007ddee206c3b264452f6ee241993cd89c342b24655063129c87179f25a6c548c0c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
